name: Ruby # ワークフロー名

on: # テストを実行するタイミングを指定
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest # job毎に必要. jobが実行される仮想環境を指定

    steps:
    - uses: actions/checkout@v2 # 使用するアクションを指定 今はv2が最新
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Hello World
      run: echo Hello World
